name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7

      - name: Install dependencies
        run: npm ci

      - name: Generate registry JSON (public/r)
        run: npm run build:shadcn

      - name: Format with Prettier
        run: npm run format

      - name: Lint & Fix
        run: npm run lint:fix

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
