name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: ./packages/cli/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/cli

      - name: Build
        run: npm run build
        working-directory: ./packages/cli

      - name: Verify package
        run: npm pack
        working-directory: ./packages/cli

      - name: Publish to NPM
        run: npm publish --access public --provenance
        working-directory: ./packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
